
"use client";

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Copy, Check, Mail } from "lucide-react";
import { useState } from "react";
import { useToast } from "@/hooks/use-toast";

type ShareDialogProps = {
  isOpen: boolean;
  onClose: () => void;
  reportId: string;
};

const WhatsAppIcon = () => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className="h-4 w-4"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.63A2 2 0 0 1 3.08 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path>
      <path d="M19.07 4.93A10 10 0 0 0 5.48 16.29" />
    </svg>
  );

export function ShareDialog({ isOpen, onClose, reportId }: ShareDialogProps) {
    const [copied, setCopied] = useState(false);
    const { toast } = useToast();
    const reportUrl = `${window.location.origin}/verify/report/${reportId}`;

    const handleCopy = () => {
        navigator.clipboard.writeText(reportUrl).then(() => {
            setCopied(true);
            toast({
                title: "Copied to clipboard!",
                description: "You can now share the link to the report.",
            });
            setTimeout(() => setCopied(false), 2000);
        });
    }
    
    const handleEmailShare = () => {
        const subject = "ASSETRAZ UK - Property Verification Report";
        const body = `Hi,\n\nPlease find the property verification report at the following link:\n\n${reportUrl}\n\nThis link contains a secure, auditable summary of the property and ownership details. This report was generated by ASSETRAZ UK, a platform for real-time property data and verification.\n\nBest regards.`;
        window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    }
    
    const handleWhatsAppShare = () => {
        const text = `Hi, here is the ASSETRAZ UK property verification report you requested: ${reportUrl}`;
        window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
    }

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Share Verification Report</DialogTitle>
          <DialogDescription>
            Choose a method to share the report. Anyone with the link can view it.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4 py-4">
            <div className="flex flex-col sm:flex-row gap-2">
                <Button onClick={handleEmailShare} variant="outline" className="flex-1">
                    <Mail className="mr-2 h-4 w-4" /> Share via Email
                </Button>
                <Button onClick={handleWhatsAppShare} variant="outline" className="flex-1">
                    <WhatsAppIcon /> Share via WhatsApp
                </Button>
            </div>
            <div className="relative">
                <div className="absolute inset-0 flex items-center">
                    <span className="w-full border-t" />
                </div>
                <div className="relative flex justify-center text-xs uppercase">
                    <span className="bg-background px-2 text-muted-foreground">
                    Or copy link
                    </span>
                </div>
            </div>
            <div className="flex items-center space-x-2">
                <Input value={reportUrl} readOnly />
                <Button onClick={handleCopy} size="icon" variant="outline">
                    {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                </Button>
            </div>
        </div>
        <DialogFooter>
          <Button variant="secondary" onClick={onClose}>Done</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
